//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooTube.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        public int VideoID { get; set; }
        public int PostID { get; set; }
        public double VideoDurationSeconds { get; set; }
        public string VideoFramzeSize { get; set; }
        public string VideoFormat { get; set; }
        public string VideoName { get; set; }
    
        public virtual Post Post { get; set; }
    }
}
